# install.packages("librarian")

librarian::shelf(adegenet    ,
                 broom       ,
                 car         ,
                 cowplot     ,
                 devtools    ,
                 DHARMa      ,
                 flextable   ,
                 ggmap       ,
                 ggpubr      ,
                 glmmTMB     ,
                 here        ,
                 janitor     ,
                 lme4        ,
                 lmerTest    ,
                 MASS        ,
                 magrittr    ,
                 memgene     ,
                 MuMIn       ,
                 officer     ,
                 patchwork   ,
                 pegas       ,
                 png         ,
                 poppr       ,
                 purrr       ,
                 raster      ,
                 rgdal       ,
                 rgeos       ,
                 rvest       ,
                 sf          ,
                 sp          ,
                 stringi     ,
                 tidyverse   ,
                 tmap        ,
                 vcfR        ,
                 vegan       ,
                 viridis
                 )
  
#library("tibble", lib.loc="~/R/win-library/3.5") 
