# install.packages("librarian")

librarian::shelf(adegenet    ,
                 broom       ,
                 car         ,
                 conStruct   ,
                 cowplot     ,
                 devtools    ,
                 DHARMa      ,
                 fields      ,
                 flextable   ,
                 fuzzyjoin   ,
                 geosphere   ,
                 ggmap       ,
                 ggpubr      ,
           #      ggsn        ,
                 glmmTMB     ,
                 grid        ,
                 gridExtra   ,
                 here        ,
                 hierfstat   ,
                 igraph      ,
                 janitor     ,
                 lme4        ,
                 lmerTest    ,
                 MASS        ,
                 magrittr    ,
                 maptiles    ,
                 memgene     ,
                 MuMIn       ,
                 officer     ,
                 patchwork   ,
                 pegas       ,
                 png         ,
                 poppr       ,
                 purrr       ,
            #     radish      ,
                 raster      ,
            #     rgdal       ,
           #      rgeos       ,
                 rvest       ,
                 sf          ,
                 sp          ,
                 stringi     ,
                 tidystats   ,
                 tidyverse   ,
                 tmap        ,
                 vcfR        ,
                 vegan       ,
                 viridis
                 )
  
#library("tibble", lib.loc="~/R/win-library/3.5") 
