# Set up notebook
## Load libraries & functions
```{r warning=F}
source(here::here("libraries.R"))
source(here::here("functions.R"))
```

## Import data
### All populations
```{r}
# this includes all 124 sampling sites- not just 122 sites included in analysis
all <- read.csv(here::here("./genomic_resources/original_sample_info/pop_map.csv"))

all_sum <- all %>%
  dplyr::group_by(population) %>%
  dplyr::summarise(n = n())
```

### Urban populations
#### Urb = dist to CC
```{r}
# urb <- read.csv(here::here("./clean_data/pop_maps/pop_map3_U_dist.csv"))

dist_cc <- read.csv(here::here("./clean_data/pop_maps/pop_map1_all_dist.csv"))

urb_sum <- dist_cc %>%
  dplyr::filter(u_r_dist == "Urban") %>%
  dplyr::group_by(patch_id) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::mutate(group = "urban")
```

#### Urb = urb score
```{r}
# urb_usc <- read.delim(here::here("./clean_data/pop_maps/pop_map3_U_usc.txt"),
#                       header = F) %>%
#   dplyr::rename("sample" = 1,
#                 "population" = 2)

urb_sc <- read.csv(here::here("./clean_data/pop_maps/pop_map1_all_usc.csv"))

  
urb_sum_usc <- urb_sc %>%
  dplyr::filter(u_r_usc == "Urban") %>%
  dplyr::group_by(patch_id) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::mutate(group = "urban")
```

### Rural populations
#### Urb = dist to CC
```{r}
#rur <- read.csv(here::here("./clean_data/pop_maps/pop_map3_R_dist.csv"))

rur_sum <- dist_cc %>%
  dplyr::filter(u_r_dist == "Rural") %>%
  dplyr::group_by(patch_id) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::mutate(group = "rural")
```

#### Urb = urb score
```{r}
# rur_usc <- read.delim(here::here("./clean_data/pop_maps/pop_map3_R_usc.txt"),
#                       header = F) %>%
#   dplyr::rename("sample" = 1,
#                 "population" = 2)


rur_sum_usc <- urb_sc %>%
  dplyr::filter(u_r_usc == "Rural") %>%
  dplyr::group_by(patch_id) %>%
  dplyr::summarise(n = n()) %>%
  dplyr::mutate(group = "rural")
```

### Combine urban, rural populations into one df
#### Urb = dist to CC
```{r}
urb_rur <- rbind(urb_sum, rur_sum) %>%
  dplyr::group_by(group, n) %>%
  dplyr::summarise(n_indiv = n()) %>%
  dplyr::mutate(group = case_when(group == "urban" ~ "Urban",
                                  group == "rural" ~ "Rural",
                                    TRUE ~ group))

```

#### Urb = urb score
```{r}
urb_rur_usc <- rbind(urb_sum_usc, rur_sum_usc) %>%
  dplyr::group_by(group, n) %>%
  dplyr::summarise(n_indiv = n()) %>%
  dplyr::mutate(group = case_when(group == "urban" ~ "Urban",
                                  group == "rural" ~ "Rural",
                                    TRUE ~ group))

```

# Plot & export
## Urb, rur pops
```{r}
#### Urb = dist to CC
dist_plot <- ggplot(urb_rur,
       aes(x = as.factor(n),
           y = n_indiv,
           fill = group)) +
  geom_bar(stat = "identity",
           position = "dodge") +
  ylab("Count") +
  xlab("Individuals per Sampling Site") +
  ylim(0, 50) +
  labs_pubr() +
  theme_pubr() +
    # remove legend
  theme(legend.position = "none") +
  geom_text(aes(label = n_indiv),
            vjust = -0.2,
            position = position_dodge(.9))


#### Urb = dist to CC
usc_plot <- ggplot(urb_rur_usc,
       aes(x = as.factor(n),
           y = n_indiv,
           fill = group)) +
  geom_bar(stat = "identity",
           position = "dodge") +
  ylab("Count") +
  xlab("Individuals per Sampling Site") +
  ylim(0, 50) +
  labs_pubr() +
  theme_pubr() +
  theme(legend.title=element_blank(),
        legend.position = "right") +
  geom_text(aes(label = n_indiv),
            vjust = -0.2,
            position = position_dodge(.9))


dist_plot +
  usc_plot + 
  patchwork::plot_layout(axes = "collect_x",
                         axis_titles = "collect") +
  plot_annotation(tag_levels = 'A')

ggsave("./Figures_Tables/sample_site_sizes/individuals_per_site_UvsR.png", 
       plot = last_plot(),
       height = 8,
       width = 20,
       units = "cm")
```

