# Set up notebook
## load libraries
```{r}
source("libraries.R")
```

# Import human population data
## Canada
### Past-2007
#### Scrape, export historic Canadian population data
Don't have to run this (already exported data to csv)
```{r}
# 1867-1970 data Source: CANSIM, table 075-0001 (persons) ii
# 1971 to present (2007) data Source: CANSIM, table 051-0001 (persons) iii

# Read the HTML code from the website
webpage <- read_html("https://www150.statcan.gc.ca/n1/pub/98-187-x/4151287-eng.htm")

# Using CSS selectors to scrape the relevant section
canada_pop_pre2007 <- html_nodes(webpage,
                            'td div') %>%
  html_text() %>%
  as.data.frame() %>%
  dplyr::rename("Year_and_Population" = 1) %T>%
  # export
  write.csv(.,
          file =
            here::here("./raw_data/human_population/Canada_human_population/human_population_Canada_raw.csv"))

canada_pop_pre2007 %<>%
  dplyr::rename("Year" = 1) %>%
  separate(.,
           "Year",
           into = c("Year", "Population"),
           sep = " +") %>%
  dplyr::filter(is.na(Population) == F) %>%

# manual data cleaning
# specific rows without spaces splitting year and population
  dplyr::mutate(Year = ifelse(row_number() == 123,
                                    1868, Year),
                Population = ifelse(row_number() == 123,
                                    "3,511,000", Population),

                Year = ifelse(row_number() == 146,
                                    1891, Year),
                Population = ifelse(row_number() == 146,
                                    "4,833,000", Population),


                Year = ifelse(row_number() == 152,
                                    1897, Year),
                Population = ifelse(row_number() == 152,
                                    "5,122,000", Population)
                ,


                Year = ifelse(row_number() == 168,
                                    1913, Year),
                Population = ifelse(row_number() == 168,
                                    "7,632,000", Population)
                ) %>%
  # remove years before 1867- census isn't uniform and numbers vary wildly
  dplyr::slice(-(1:121)) %>%

# Split the Population column by comma
  separate(.,
           "Population",
           into = c("Population1", "Population2", "Population3"),
           sep = ",+") %>%
  # only keep last 3 digits before last comma- there were some superscripts in original table (e.g., 50, 51...) that were added on as extra values to these population counts and have to be removed
  dplyr::mutate(Population3 = str_sub(
    Population3, start = 1, end = 3)) %>%
  dplyr::mutate(Population = paste0(Population1, Population2, Population3)) %>%
  dplyr::select(-c(Population1, Population2, Population3)) %>%
    # convert to years before present, just like x axis in Ne dfs
  dplyr::mutate(Population = as.numeric(Population),
                Year = as.numeric(Year),
                years_before_present = 2023 - Year)

  # export
canada_pop_pre2007 %>%
  write.csv(.,
          file =
            here::here("./clean_data/human_pop_data/human_population_Canada_clean.csv"))
```

#### Import cleaned data here
```{r}
canada_pop_pre2007 <- read.csv(here::here("./clean_data/human_pop_data/human_population_Canada_clean.csv"))
```

### 2008-2022
```{r}
all_canada_pop <- read.csv(here::here("./raw_data/human_population/Canada_human_population/human_population_Canada_raw_after2007.csv")) %>%
  # keep only Q1 values
  dplyr::filter(grepl('Q1', Geography)) %>%
  # remove Q1
  dplyr::mutate(Geography = str_replace(Geography,
                                        "Q1 ", "")) %>%
  dplyr::rename(Year = 1,
                Population = 2) %>%
    # convert to years before present, just like x axis in Ne dfs
  dplyr::mutate(Population = gsub(",", "", Population),
                Population = as.numeric(Population),
                Year = as.numeric(Year),
                years_before_present = 2023 - Year)
```

### Past-2022
```{r}
  # join with older data
all_canada_pop %<>%
  dplyr::full_join(canada_pop_pre2007,
                   .,
                   by = c("Year", "Population", "years_before_present")) 


# export
all_canada_pop %>%
  write.csv(.,
          file =
            here::here("./clean_data/human_pop_data/human_population_Canada_clean.csv"))
```

## Ontario
```{r}
ontario_pop <- read.csv(here::here("./raw_data/human_population/Ontario_human_population/ontario_pop.csv")) %>%
  dplyr::mutate(Population = gsub(",", "", Population)) %>%
  dplyr::mutate(Year = as.numeric(Year),
                Population = as.numeric(Population),
                years_before_present = 2023 - Year)

# export
ontario_pop %>%
  write.csv(.,
          file =
            here::here("./clean_data/human_pop_data/human_population_Ontario_clean.csv"))
```

## Toronto
```{r}
toronto_pop <- read.csv(here::here("./raw_data/human_population/Toronto_human_population_Wikipedia/Toronto_city_population.csv")) %>%
  dplyr::select(Year, City) %>%
  dplyr::rename(Population = City) %>%
  dplyr::mutate( years_before_present = 2023 - Year)


  # export
toronto_pop %>%
  write.csv(.,
          file =
            here::here("./clean_data/human_pop_data/human_population_Toronto_clean.csv"))
```

# Export figures
## Canada
```{r}
ggplot(
    all_canada_pop,
    aes(
      x = years_before_present,
      y = Population/1000000))  +
    # geom_segment( # add vertical line at 1867
    #   aes(
    #     x = 156,
    #     xend = 156,
    #     y = 0,
    #     yend = 40),
    #   color = "blue",
    #   linetype = 4 ) +
    geom_point(size = 0.75) +
      geom_line() +
    scale_y_continuous(labels = scales::comma,
                       limits = c(0, NA)) +
    xlab("Years before present") +
    ylab("Human population in\n Canada (millions)") +
    theme_bw() +
    labs_pubr() +
    scale_x_continuous(limits = c(0, 156),
                       sec.axis = sec_axis(~ 2023 - .,
                                 name = "Year",
                                 breaks = c(2023, 2000, 1950, 1900, 1867))) +
    theme(plot.background = element_rect(
            colour = "black", fill = "white", size = 1))

ggsave(last_plot(),
       file = here::here("./Figures_Tables/Stairway_plot/Human_population/Canada_population.png"),
       height = 5,
         width = 7,
         dpi = 200)
  
```

## Ontario
```{r}
ggplot(
    ontario_pop,
    aes(
      x = years_before_present,
      y = Population/1000000))  +
    # geom_segment( # add vertical line at 1867
    #   aes(
    #     x = 156,
    #     xend = 156,
    #     y = 0,
    #     yend = 40),
    #   color = "blue",
    #   linetype = 4 ) +
    geom_point(size = 0.75) +
    geom_line() +
    scale_y_continuous(limits = c(0, 15)) +
    xlab("Years before present") +
    ylab("Human population in\n Ontario (millions)") +
    theme_bw() +
    labs_pubr() +
    scale_x_continuous(limits = c(0, 200),
                       sec.axis = sec_axis(~ 2023 - .,
                                 name = "Year",
                                 breaks = c(2023, 2000, 1950, 1900, 1850, 1824))) +
    theme(plot.background = element_rect(
            colour = "black", fill = "white", size = 1))

ggsave(last_plot(),
       file = here::here("./Figures_Tables/Stairway_plot/Human_population/Ontario_population.png"),
       height = 5,
         width = 7,
         dpi = 200)
  
```


## Toronto
```{r}
ggplot(
    toronto_pop,
    aes(
      x = years_before_present,
      y = Population/1000000))  +
    geom_point(size = 0.75) +
    geom_line() +
    scale_y_continuous(limits = c(0, 3)) +
    xlab("Years before present") +
    ylab("Human population in\n Toronto (millions)") +
    theme_bw() +
    labs_pubr() +
    scale_x_continuous(limits = c(0, 200),
                       sec.axis = sec_axis(~ 2023 - .,
                                 name = "Year",
                                 breaks = c(2023, 2000, 1950, 1900, 1850, 1824))) +
    theme(plot.background = element_rect(
            colour = "black", fill = "white", size = 1))

ggsave(last_plot(),
       file = here::here("./Figures_Tables/Stairway_plot/Human_population/Toronto_population.png"),
       height = 5,
         width = 7,
         dpi = 200)
```