# Set up notebook
## Load packages
```{r}
source(here::here("libraries.R"))
source(here::here("functions.R"))
```

## Import data
```{r}
urb <- read.csv(here::here("./clean_data/urb_metrics.csv")) %>%
  dplyr::mutate(site_id = as.factor(site_id),
                patch_id = as.factor(patch_id),
                urb_rur = as.factor(urb_rur),
                quadrant = as.factor(quadrant),
                river_valley = as.factor(river_valley)
                ) 

# the commented-out all_sites included pop map 3, which excluded 2 sampling sites. The following map will show ALL 124 sampling sites- including the two that were ultimately eliminated due to removing 7 individuals from the analysis because of low quality sequencing or high IBD.
# all_sites <- read.csv(here::here("./genomic_resources/pop_map3.csv")) %>%
#      # rename col 1
#   dplyr::rename(pop_id = 2) %>%
#   dplyr::mutate(pop_id = as.factor(pop_id)) %>%
# ### Add "MW" to numeric populations
#   add_MW_IDs()


all_sites <- read.csv(here::here("./genomic_resources/original_sample_info/pop_map.csv")) %>%
    # rename col 1
  dplyr::rename(pop_id = 2) %>%
  dplyr::mutate(pop_id = as.factor(pop_id)) %>%
### Add "MW" to numeric populations
  add_MW_IDs()

# keep only the sampling sites for which I sequenced DNA
sites <- left_join(all_sites,
                   urb)

# check
length(unique(sites$patch_id))


max(sites$City_dist) # max City_dist
min(sites$City_dist) # min City_dist

max(sites$urb_score) # max Urb Score
min(sites$urb_score) # min Urb Score

# Number of rural vs urban sites
# first, make df with only unique sites
sites_unique <- sites %>%
  dplyr::group_by(patch_id) %>%
  dplyr::summarise(u_r_dist = first(u_r_dist),
                   u_r_usc = first(u_r_usc))

sum(sites_unique$u_r_dist == "Urban")
sum(sites_unique$u_r_dist == "Rural")
sum(sites_unique$u_r_usc == "Urban")
sum(sites_unique$u_r_usc == "Rural")

```

# Sampling site maps
## Main map: Urban/rural symbols
### Based on distance to CC
```{r}

# Convert the dataframe to an sf object
sites <- sf::st_as_sf(sites,
                  coords = c("long", "lat"),
                  crs = 4326)

bbox <- c(-80.3, 43.15, -78.3, 44.2)

tmap_mode("plot")

# get map tiles for basemap
my_tiles = get_tiles(sites,
                    provider = "Esri.WorldImagery",
                   #  provider = "Esri.NatGeoWorldMap",
                  #   provider = "Esri.WorldStreetMap",
                   #  provider = "OpenStreetMap",
                     zoom = 10,
                     crop = FALSE)

# basemap
tm_shape(my_tiles,
         raster.downsample = TRUE ) +
  tm_rgb(alpha = 0.8) + 
  tm_grid(lines = F,
          x = c(-80.5, -80, -79.5, -79, -78.5 )) +
  # sample sites
  tm_shape(sites,
           bbox = bbox) +
  tm_symbols(col = "u_r_dist", 
             shape = "u_r_dist",
             size = 0.4,
             shapes = c(21, 24),
             palette = c("Urban" = "cyan", "Rural" = "red"),
         # title.shape = "Group",
             legend.shape.show = FALSE,
		         legend.col.show = FALSE) +
  tm_add_legend(type = "symbol",
                shape = c(21, 24), 
                col = c("cyan", "red"), 
                labels = c("Urban", "Rural"),
                title = "Group") +
  
  # layout
  tm_layout(frame = TRUE,
            # legend.position = c(0.02, 0.7),
            legend.position = c(0.75, 0),
            legend.title.size = 0.95,
            inner.margins = c(0.0, 0.0, 0.0, 0.0),
            legend.bg.color = "white",
          legend.bg.alpha = 0.4) +
  tm_compass(type = "4star",
             size = 1, 
             position = c("left", "top")) +
  tm_scale_bar(position = c(0,-0.03),
              # position = c(0.3, -0.03),
               text.color = "black",
               bg.color = "white",
               bg.alpha = 0.4#,
             #  bg.alpha = 0,
             #  text.size = 1
             ) 


# Export
dev.copy2pdf(file = here::here("./Figures_Tables/sample_site_map/pops_urb_rur_based-on-city_dist.pdf"),
             width = 5, height = 4)

```

### Based on urb score
```{r}
tmap_mode("plot")

# basemap
tm_shape(my_tiles,
         raster.downsample = TRUE ) +
  tm_rgb(alpha = 0.8) + 
  tm_grid(lines = F,
          x = c(-80.5, -80, -79.5, -79, -78.5 )) +
  # sample sites
  tm_shape(sites,
           bbox = bbox) +
  tm_symbols(col = "u_r_usc", 
             shape = "u_r_usc",
             size = 0.4,
             shapes = c(21, 24),
             palette = c("Urban" = "cyan", "Rural" = "red"),
         # title.shape = "Group",
             legend.shape.show = FALSE,
		         legend.col.show = FALSE) +
  tm_add_legend(type = "symbol",
                shape = c(21, 24), 
                col = c("cyan", "red"), 
                labels = c("Urban", "Rural"),
                title = "Group") +
  
  # layout
  tm_layout(frame = TRUE,
            # legend.position = c(0.02, 0.7),
            legend.position = c(0.75, 0),
            legend.title.size = 0.95,
            inner.margins = c(0.0, 0.0, 0.0, 0.0),
            legend.bg.color = "white",
          legend.bg.alpha = 0.4) +
  tm_compass(type = "4star",
             size = 1, 
             position = c("left", "top")) +
  tm_scale_bar(position = c(0,-0.03),
              # position = c(0.3, -0.03),
               text.color = "black",
               bg.color = "white",
               bg.alpha = 0.4#,
             #  bg.alpha = 0,
             #  text.size = 1
             ) 


# Export
dev.copy2pdf(file = here::here("./Figures_Tables/sample_site_map/pops_urb_rur_based-on-urb_score.pdf"),
             width = 5, height = 4)
```

## Main map: Distance to CC
```{r}
# basemap
tm_shape(my_tiles,
         raster.downsample = TRUE ) +
  tm_rgb(alpha = 0.8) + 
  tm_grid(lines = F,
          x = c(-80.5, -80, -79.5, -79, -78.5 )) +
  # sample sites
  tm_shape(sites,
           bbox = bbox) +
  tm_symbols(col = "City_dist", 
             size = 0.4,
          title.col = "Distance to\n the City\n Center (km)",
		         legend.col.show = TRUE,
          style = "cont") +
  # tm_add_legend(type = "symbol",
  #           #    col = c("cyan", "red"), 
  #               labels = c("Urban", "Rural"),
  #               title = "Group") +
  
  # layout
  tm_layout(frame = TRUE,
            legend.position = c(0.77, 0),
            # legend.title.size = 0.73,
             legend.text.size = 1,
            legend.width = 0.4,
            legend.height = 0.45,
            inner.margins = c(0.0, 0.0, 0.0, 0.0),
            legend.bg.color = "white",
          legend.bg.alpha = 0.4) +
  tm_compass(type = "4star",
             size = 1, 
             position = c("left", "top")) +
  tm_scale_bar(position = c(0,-0.03),
              # position = c(0.3, -0.03),
               text.color = "black",
               bg.color = "white",
               bg.alpha = 0.4#,
             #  bg.alpha = 0,
             #  text.size = 1
             ) 

# Export
dev.copy2pdf(file = here::here("./Figures_Tables/sample_site_map/gta_sampling_citydist.pdf"),
             width = 5, height = 4)
```


## Main map: urbanization score
```{r}
# basemap
tm_shape(my_tiles,
         raster.downsample = TRUE ) +
  tm_rgb(alpha = 0.8) + 
  tm_grid(lines = F,
          x = c(-80.5, -80, -79.5, -79, -78.5 )) +
  # sample sites
  tm_shape(sites,
           bbox = bbox) +
  tm_symbols(col = "urb_score", 
          size = 0.4,
          title.col = "Urbanization\n Score",
		      legend.col.show = TRUE,
          palette = "PuOr",
		      legend.col.reverse = TRUE,
          style = "cont") +
  
  # layout
  tm_layout(frame = TRUE,
            legend.position = c(0.77, 0),
            # legend.title.size = 0.73,
             legend.text.size = 1,
            legend.width = 0.4,
            legend.height = 0.45,
            inner.margins = c(0.0, 0.0, 0.0, 0.0),
            legend.bg.color = "white",
          legend.bg.alpha = 0.4) +
  tm_compass(type = "4star",
             size = 1, 
             position = c("left", "top")) +
  tm_scale_bar(position = c(0,-0.03),
              # position = c(0.3, -0.03),
               text.color = "black",
               bg.color = "white",
               bg.alpha = 0.4#,
             #  bg.alpha = 0,
             #  text.size = 1
             ) 


# Export
dev.copy2pdf(file = here::here("./Figures_Tables/sample_site_map/gta_sampling_urbscore.pdf"),
             width = 5, height = 4)

```