# Set up notebook
## Load libraries & functions
```{r warning=F}
source(here::here("libraries.R"))
```

## Import data
### Urb = dist to CC
```{r}
# Urban pop vs. Rural pop
snp_fst_UvsR <- read.table(here::here("./results/pi_fst_TajD_estimates/fst/fst_mmaf0.05_R0.75_no-IBD_vcf-all/fst_urb_vs_rur_dist/urb_vs_rur.weir.fst")) %>%
  janitor::row_to_names(row_number = 1) %>%
  janitor::clean_names() %>%
  dplyr::rename(fst = 3) %>%
    dplyr::filter(fst != "-nan") 

# Urban subpopulations
snp_fst_U <- read.table(here::here("./results/pi_fst_TajD_estimates/fst/fst_mmaf0.05_R0.75_no-IBD_vcf-all/fst_urb_dist/urb_.weir.fst")) %>%
  janitor::row_to_names(row_number = 1) %>%
  janitor::clean_names() %>%
  dplyr::rename(fst = 3) %>%
    dplyr::filter(fst != "-nan") 

# Rural subpopulations
snp_fst_R <- read.table(here::here("./results/pi_fst_TajD_estimates/fst/fst_mmaf0.05_R0.75_no-IBD_vcf-all/fst_rur_dist/rur_.weir.fst")) %>%
  janitor::row_to_names(row_number = 1) %>%
  janitor::clean_names() %>%
  dplyr::rename(fst = 3) %>%
    dplyr::filter(fst != "-nan") 
```

### Urb = urb score
```{r}
# Urban pop vs. Rural pop
snp_fst_UvsR_usc <- read.table(here::here("./results/pi_fst_TajD_estimates/fst/fst_mmaf0.05_R0.75_no-IBD_vcf-all/fst_urb_vs_rur_usc/urb_vs_rur_usc.weir.fst")) %>%
  janitor::row_to_names(row_number = 1) %>%
  janitor::clean_names() %>%
  dplyr::rename(fst = 3) %>%
    dplyr::filter(fst != "-nan") 

# Urban subpopulations
snp_fst_U_usc <- read.table(here::here("./results/pi_fst_TajD_estimates/fst/fst_mmaf0.05_R0.75_no-IBD_vcf-all/fst_urb_usc/urb_usc.weir.fst")) %>%
  janitor::row_to_names(row_number = 1) %>%
  janitor::clean_names() %>%
  dplyr::rename(fst = 3) %>%
    dplyr::filter(fst != "-nan") 

# Rural subpopulations
snp_fst_R_usc <- read.table(here::here("./results/pi_fst_TajD_estimates/fst/fst_mmaf0.05_R0.75_no-IBD_vcf-all/fst_rur_usc/rur_usc.weir.fst")) %>%
  janitor::row_to_names(row_number = 1) %>%
  janitor::clean_names() %>%
  dplyr::rename(fst = 3) %>%
    dplyr::filter(fst != "-nan") 
```

# Create the fst dfs
## mean fst df
```{r}
fst <- data.frame(
  fst = c(
    # urb = dist
    mean(as.numeric(as.character(snp_fst_UvsR$fst)), na.rm = T),
    mean(as.numeric(as.character(snp_fst_U$fst)), na.rm = T),
    mean(as.numeric(as.character(snp_fst_R$fst)), na.rm = T),
    # urb = usc
    mean(as.numeric(as.character(snp_fst_UvsR_usc$fst)), na.rm = T),
    mean(as.numeric(as.character(snp_fst_U_usc$fst)), na.rm = T),
    mean(as.numeric(as.character(snp_fst_R_usc$fst)), na.rm = T)
    ), 
  urbanization = c("Distance to City Center",
                   "Distance to City Center",
                   "Distance to City Center",
                   "Urbanization Score",
                   "Urbanization Score",
                   "Urbanization Score"),
  category = c(
    "Urb vs. Rural",
    "Within Urban",
    "Within Rural",
    "Urb vs. Rural",
    "Within Urban",
    "Within Rural"),
 SE = c(
   sd(snp_fst_UvsR$fst) / sqrt(length(snp_fst_UvsR$fst)),
   sd(snp_fst_U$fst) / sqrt(length(snp_fst_U$fst)),
   sd(snp_fst_R$fst) / sqrt(length(snp_fst_R$fst)),
   sd(snp_fst_UvsR_usc$fst) / sqrt(length(snp_fst_UvsR_usc$fst)),
   sd(snp_fst_U_usc$fst) / sqrt(length(snp_fst_U_usc$fst)),
   sd(snp_fst_R_usc$fst) / sqrt(length(snp_fst_R_usc$fst))
 ))


```

## All site-specific fst estimates
```{r}
 # can't figure out how to automate adding df's name as col
 snp_fst_UvsR %<%
   dplyr::mutate(dataset = "snp_fst_UvsR")

 snp_fst_UvsR_usc %<%
   dplyr::mutate(dataset = "snp_fst_UvsR_usc")
 
 snp_fst_U %<%
   dplyr::mutate(dataset = "snp_fst_U")
 
 snp_fst_U_usc %<%
   dplyr::mutate(dataset = "snp_fst_U_usc")
 
 snp_fst_R %<%
   dplyr::mutate(dataset = "snp_fst_R")
 
 snp_fst_R_usc %<%
   dplyr::mutate(dataset = "snp_fst_R_usc")

# combine into one df
all_dfs <- rbind(snp_fst_UvsR,
                snp_fst_UvsR_usc,
                snp_fst_U,
                snp_fst_U_usc,
                snp_fst_R,
                snp_fst_R_usc) %>%
  dplyr::mutate(fst = as.numeric(fst))

```

# Visualize fst
## Point values
```{r}

ggplot(fst, 
       aes(x = category,
           y = fst,
           label = round(fst, 3))) +
  geom_errorbar(aes(ymin = fst - SE,
                    ymax = fst + SE),
                color = "black",
                width = 0.2) +
    geom_point(aes(color = category),
             size = 4) +
  ylab(expression(F[ST])) +
  ylim(NA, 0.1) +
  theme_pubr() +
  xlab("") +
  theme(legend.position = "none") +
  scale_color_manual(
        values = c("#6633CC", "#FF3333", "#00CCFF")
    # values = c("Urb vs. Rural", "Within Rural", "Within Urban",
                                ) +
  geom_text(hjust = 0.5, vjust = -1.75) +
  facet_wrap(vars(urbanization))


ggsave(here::here("./Figures_Tables/fst/fst.png"), 
       plot = last_plot(),
       width = 20,
       height = 8,
       units = "cm")

```

## Violin plot
```{r}

ggplot(all_dfs, 
       aes(x = dataset,
           y = fst,
           fill = dataset)) +
  geom_violin(aes(color = dataset),
              size = 1,
              width = 1) +
  geom_boxplot(width = 0.05,
               color = "black") +
  ylab(expression(F[ST])) +
  theme_pubr() +
  theme(legend.position = "none") +
  scale_color_brewer(palette = "Paired") +
  scale_fill_brewer(palette = "Paired") +
  scale_x_discrete(labels=c("Rural\n(D)",
                            "Rural\n(U)",
                            "Urban\n(D)",
                            "Urban\n(U)",
                            "Urban vs. Rural\n(D)",
                            "Urban vs. Rural\n(U)"))


ggsave(here::here("./Figures_Tables/fst/fst_violins.png"),
       plot = last_plot(),
       width = 25,
       height = 8,
       units = "cm")

```

## Dot plot
```{r}

ggplot(all_dfs, 
       aes(x = dataset,
           y = fst,
           fill = dataset)) +
  geom_boxplot(width = 0.7,
               color = "black") +
      geom_jitter(aes(fill = dataset),
                  size=0.7, 
                  alpha=0.9,
                  shape = 21) +
  ylab(expression(F[ST])) +
  theme_pubr() +
  theme(legend.position = "none") +
  scale_fill_brewer(palette = "Paired") +
  scale_x_discrete(labels=c("Rural\n(D)",
                            "Rural\n(U)",
                            "Urban\n(D)",
                            "Urban\n(U)",
                            "Urban vs. Rural\n(D)",
                            "Urban vs. Rural\n(U)"))



ggsave(here::here("./Figures_Tables/fst/fst_violins_dots.png"),
       plot = last_plot(),
       width = 25,
       height = 8,
       units = "cm")

```

