# Set up notebook
## Load libraries & functions
```{r}
source(here::here("libraries.R"))

library(hierfstat)
```

## Import genetic data
```{r}
vcf <- read.vcfR(
  here::here("./summary_stats/output_populations_no-IBD/mmaf0.05_R0.75/populations.snps.vcf"),
  verbose = FALSE)

## Convert vcf to genind object
my_genind <- vcfR2genind(vcf)



# read in pop map with populations
pops <- read.csv(here("./genomic_resources/pop_map3.csv"))

# pop map with urban/rural designations
pops_UR <- read.delim(here("./clean_data/pop_map3_UR_dist.txt"),
                      header = F) %>%
  dplyr::rename("sample" = 1,
                "urban_rural" = 2)

# join pop maps
pops <- full_join(pops,
                  pops_UR,
                  by = "sample")


# add pops to genind
strata(my_genind) <- pops
pop(my_genind) <- pops[,"population"]
```

# Hierfstat
## Create f-statistic matrix
```{r}
# convert it to correct format for package
formatted_genind <- genind2hierfstat(my_genind)

# make sure levels are from outermost to innermost
fsts <- varcomp.glob(levels = data.frame(pops$urban_rural,
                                 pops$population),
             loci = formatted_genind[,-1],
             diploid = TRUE)

# look at variance components summed over all loci
fsts$overall %>%
  as.data.frame()

# look at f-statistic matrix
fsts$F %>%
  as.data.frame()

# p-value
# this isn't working- 0s and p = 1
test.between(formatted_genind[,-1],
       test.lev = pops$urban_rural,
       rand.unit = pops$population,
       nperm = 100) 

```

## Calculate population-specific fst
```{r}
betas(formatted_genind)$betaiovl %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  dplyr::rename("sampling_site" = 1,
                "fst" = 2) %>%
  dplyr::arrange(fst)

```

## Calculate pairwise Fst
```{r}
# takes about 6 hours
pairwise_fst_matrix <- genet.dist(my_genind, method = "WC84")

```

# Export f-statistics
## Hierarchical
```{r}
# first, turn off scientific notation
options(scipen=999) 

# then, export matrix of hierarchical F-statistics type-coefficients
fsts$F %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  dplyr::rename("Level" = 1,
                "Urban/Rural Group" = 2,
                "Sampling Site" = 3,
                "Individual" = 4) %>%
  dplyr::mutate_if(is.numeric, round, 4) %>%
  dplyr::mutate(Level = case_when(Level == "pops.urban_rural" ~ "Urban/Rural Group",
                                  Level == "pops.population" ~ "Sampling Site",
                         TRUE ~ Level)) %>%
  dplyr::mutate_all(~ ifelse(. == 0, "-", .)) %>%
  flextable() %>%
  autofit() %>%
  save_as_docx(path = here::here("./Figures_Tables/fst/hierfstat.docx"))

```

## Pairwise fst
```{r}
# transform dist object into matrix, then export
full_matrix <- pairwise_fst_matrix %>%
  as.matrix() %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  dplyr::rename("population" = 1)

write.csv(full_matrix,
          file = here::here("./Figures_Tables/fst/pairwise_fst_matrix.csv"))
```

