# Set up notebook
## Load libraries & functions
```{r warning=F}
source(here::here("libraries.R"))
source(here::here("functions.R"))

# devtools::install_github("AnushaPB/wingen", build_vignettes = TRUE)
# install.packages('terra', repos='https://rspatial.r-universe.dev')
library(wingen)

```

## Import data
```{r}
# urbanization data
urb <- read.csv(here("./clean_data/urb_metrics.csv")) %>%
  dplyr::rename("pop_id" = "patch_id")

# pop map
pops <- read.csv(here("./genomic_resources/pop_map3.csv"))

# vcf
vcf <- read.vcfR(
  here::here("./summary_stats/output_populations_no-IBD/mmaf0.05_R0.75/populations.snps.vcf"),
  verbose = FALSE)

```

# Run wingen
```{r}
# Run moving window calculations of pi with rarefaction
wgd <- window_gd(lotr_vcf,
  lotr_coords,
  lotr_lyr,
  stat = "pi",
  wdim = 7,
  fact = 3,
  rarify = TRUE
)

# Use plot_gd() to plot the genetic diversity layer and plot_count() to plot the sample counts layer
par(mfrow = c(1, 2), oma = rep(0, 4), mar = rep(0, 4), pty = "s")
plot_gd(wgd, main = "Moving window pi", legend.width = 1.5)
plot_count(wgd, main = "Moving window sample counts", legend.width = 1.5)
```

