# Set up notebook
## Load libraries & functions
```{r warning=F}
source(here::here("libraries.R"))
```

# Calculate Watterson's theta

R = 0.5
mmaf = 0.0078125 (2/256)

## Global (all sites in one large population)
```{r}
theta_w <- pegas::theta.s(
  x = (2835/352769), # segregating sites
  
  # (in the pi_fst_TajD_estimates/pi/global_pi/global_pi_vcf-all/populations.sumstats_summary.tsv file, this is variant sites/all sites)

  n = 256,  # sequences
  
  # (in the global_pi_vcf-all/populations.log file, this is the number of samples)
  
  variance = TRUE
)

theta_w
# output: 
# theta = 0.0013130465  
# variance = 0.0002146102
```

## Urban vs. Rural (based on dist to cc < 35 km)
### Urban
```{r}
theta_w_urb <- pegas::theta.s(
  x = (2835/352769), # segregating sites
  
  # (in the UR_dist_pi_vcf-all/populations.sumstats_summary.tsv file, this is variant sites/all sites)

  n = 150,  # sequences
  
  # (counted number of urban samples in the pop_map3 file with create_popmaps.Rmd)
  
  variance = TRUE
)

theta_w_urb
# output: 
# theta = 0.0014390546   
# variance = 0.0002577954
```

### Rural
```{r}
theta_w_rur <- pegas::theta.s(
  x = (2835/352769), # segregating sites
  
  # (in the UR_dist_pi_vcf-all/populations.sumstats_summary.tsv file, this is variant sites/all sites)

  n = 106,  # sequences
  
  # (counted number of rural samples in the pop_map3 file with create_popmaps.Rmd)
  
  variance = TRUE
)

theta_w_rur
# output: 
# theta = 0.0015348601    
# variance = 0.0002932804
```

## Urban vs. Rural (based on urbanization score)
### Urban
```{r}
theta_w_urb2 <- pegas::theta.s(
  x = (2835/352769), # segregating sites
  
  # (in the UR_usc_pi_vcf-all/populations.sumstats_summary.tsv file, this is variant sites/all sites)

  n = 141,  # sequences
  
  # (counted number of urban samples in the pop_map3 file with create_popmaps.Rmd)
  
  variance = TRUE
)

theta_w_urb2
# output: 
# theta = 0.0014552339    
# variance = 0.0002636273
```

### Rural
```{r}
theta_w_rur2 <- pegas::theta.s(
  x = (2835/352769), # segregating sites
  
  # (in the UR_usc_pi_vcf-all/populations.sumstats_summary.tsv file, this is variant sites/all sites)

  n = 115,  # sequences
  
  # (counted number of rural samples in the pop_map3 file with create_popmaps.Rmd)
  
  variance = TRUE
)

theta_w_rur2
# output: 
# theta = 0.0015112321     
# variance = 0.0002843162
```

# Export
## Create df with theta Ws
```{r}

neaten_df <- function(theta_w_output, scale, urbanization){
  theta_w_output %<>%
    as.data.frame() %>%
  dplyr::rename("estimate" = 1) %>%
  dplyr::mutate(value = c("Watterson's theta", 
                          "Variance"),
                Group = scale,
                Urbanization = urbanization)
}

theta_w <- neaten_df(theta_w,
                     "Global",
                     "-")

theta_w_urb <- neaten_df(theta_w_urb,
                         "Urban",
                         "Distance to City Center") 

theta_w_rur <- neaten_df(theta_w_rur,
                         "Rural",
                         "Distance to City Center")

theta_w_urb2 <- neaten_df(theta_w_urb2,
                         "Urban",
                         "Urbanization Score") 

theta_w_rur2 <- neaten_df(theta_w_rur2,
                         "Rural",
                         "Urbanization Score")

thetas <- rbind(theta_w,
                theta_w_urb,
                theta_w_rur,
                theta_w_urb2,
                theta_w_rur2) %>%
  dplyr::select(Group, Urbanization, value, estimate) %>%
  dplyr::mutate(estimate = round(estimate, 5)) %>%
  tidyr::pivot_wider(names_from = value,
                     values_from = estimate) %>%
  slice(c(1,2,4,3,5))
```

## Export theta W only
```{r}
thetas %>%
  flextable::flextable() %>%
  flextable::align(align = "center", i = c(1:5), part = "body") %>%
  flextable::align(align = "left", j = 1:2, part = "all") %>%
  flextable::align(align = "center", i = 1, j = c(3,4), part = "header") %>%
  hline(i = c(1,3)) %>%
  flextable::autofit() %>%
  flextable::save_as_docx(path = here::here(
    "./Figures_Tables/gen_diversity/wattersons_theta.docx"))
```

## Export theta W and pi
### Add pi values
```{r}
# values from ./results/pi_fst_TajD_estimates/pi/dist_to_city_center/UR_dist_pi_vcf-all/populations.sumstats_summary.tsv, and from analogous tsvs

# Global pi-----
pi_global <- 0.00091
  
# Urb = dist to city center-----
## Urban group
pi_dist_urb <- 0.00091

## Rural group
pi_dist_rur <- 0.00090

# Urb = dist to city center-----
## Urban group
pi_usc_urb <- 0.00091

## Rural group
pi_usc_rur <- 0.00090

pis <- thetas %>%
  dplyr::select(Group:Urbanization) %>%
  dplyr::mutate(Pi = c(pi_global,
                       pi_dist_urb,
                       pi_usc_urb,
                       pi_dist_rur,
                       pi_usc_rur))
```

### Export
```{r}
thetas %>%
  dplyr::full_join(.,
                   pis,
                   by = c("Group", "Urbanization")) %>%
  dplyr::select(-Variance) %>%
  flextable::flextable() %>%
  flextable::align(align = "center", i = c(1:5), part = "body") %>%
  flextable::align(align = "left", j = 1:2, part = "all") %>%
  flextable::align(align = "center", i = 1, j = c(3,4), part = "header") %>%
  hline(i = c(1,3)) %>%
  flextable::autofit() %>%
  flextable::save_as_docx(path = here::here(
    "./Figures_Tables/gen_diversity/theta_w_and_pi.docx"))
```